version: '3'

networks:

  default:

services:
  email_challenge:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    container_name: email_challenge
    networks:
      - default
    ports:
      - '8384:80'
    restart: unless-stopped
    volumes:
      - ../src/:/var/www/html/
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MARIADB_DATABASE: emails
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    container_name: rabbitmq
    ports:
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  mydb:
  rabbitmq: